# docker-compose.yml

version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: guest
      PGRST_DB_POOL: 10
      PGRST_SERVER_HOST: 0.0.0.0
      PGRST_SERVER_PORT: 3000
      PGRST_JWT_SECRET: "FKgsTuWapKw6AbrzHzl783LAXGwgAtdu"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    env_file: .env
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
